//
// Created by Igor on 2/10/2018.
//

#ifndef TCP_CHAT_STYLE_HPP
#define TCP_CHAT_STYLE_HPP

#define DEFAULT_EDIT_STYLE (WS_VISIBLE | WS_CHILD | ES_AUTOHSCROLL | WS_BORDER)
#define DEFAULT_TEXTAREA_STYLE (WS_CHILD | WS_VISIBLE | WS_VSCROLL | WS_HSCROLL | ES_MULTILINE | ES_AUTOVSCROLL | ES_AUTOHSCROLL)
#define DEFAULT_BUTTON_STYLE (WS_VISIBLE | WS_CHILD | BS_FLAT)

#endif //TCP_CHAT_STYLE_HPP
